"""
OpenClaw Core Agent
The self-evolving intelligence engine.
"""

import json
import os
import random
from typing import Dict, Any, List
from rich.console import Console
from rich.panel import Panel
from rich.progress import track

from .ollama_client import OllamaClient
from .memory import Memory

console = Console()

class OpenClawAgent:
    def __init__(self, model: str = "llama3.2:3b", base_dir: str = "."):
        self.model = model
        self.client = OllamaClient(model=model)
        self.memory = Memory(base_dir=os.path.join(base_dir, "memory"))
        self.cycle = 0
        self.performance = 50.0
        self.system_prompt = self.memory.get_best_prompt()
        
        self.evolution_dir = os.path.join(base_dir, "evolution
")
        os.makedirs(self.evolution_dir, exist_ok=True)

    def think(self, task: str = "Improve myself") -> str:
        """Core reasoning step"""
        messages = [
            {"role": "system", "content": self.system_prompt},
            {"role": "user", "content": f"Current cycle: {self.cycle}. Task: {task}. What should I do next to become more powerful?"}
        ]
        return self.client.chat(messages, temperature=0.75)

    def act(self, thought: str) -> str:
        """Execute an action based on thought (simulated + real tool use)"""
        if "create tool" in thought.lower() or "new skill" in thought.lower():
            return self._create_new_skill(thought)
        elif "improve prompt" in thought.lower():
            return self._evolve_prompt()
        else:
            return f"Executed creative action: {thought[:100]}"

    def reflect(self, action_result: str) -> Dict[str, Any]:
        """Self-reflection and scoring"""
        recent = self.memory.get_recent_experiences(5)
        summary = "\n".join([f"Cycle {e['cycle']}: {e['action'][:80]} (score: {e['score']})" for e in recent])
        
        reflection = self.client.reflect_and_score(
            f"Thought: {action_result}\n\nRecent history:\n{summary}"
        )
        
        self.performance = reflection.get("score", 50)
        return reflection

    def evolve(self, reflection: Dict[str, Any]):
        """Apply improvements"""
        if self.performance > 75 and random.random() > 0.6:
            new_prompt = self.client.generate_improvement(
                self.system_prompt, 
                self.performance,
                "\n".join([e['reflection'] for e in self.memory.get_recent_experiences(3)])
            )
            if len(new_prompt) > 100:
                self.system_prompt = new_prompt
                self.memory.save_evolved_prompt(self.cycle, new_prompt, self.performance)
                console.print(Panel("[bold green]SYSTEM PROMPT EVOLVED![/bold green]", title="Evolution"))

        if self.performance > 80 and random.random() > 0.7:
            self._create_new_skill("Autonomous capability discovery")

    def run_cycle(self):
        self.cycle += 1
        console.rule(f"[bold cyan]OpenClaw Cycle {self.cycle}[/bold cyan]")

        thought = self.think()
        console.print(Panel(thought[:300] + "...", title="Thought", border_style="blue"))

        action = self.act(thought)
        console.print(Panel(action, title="Action", border_style="green"))

        reflection = self.reflect(action)
        console.print(Panel(f"Score: {reflection.get('score', 0)}/100\nImprovements: {reflection.get('improvements', [])} ", 
                           title="Reflection", border_style="yellow"))

        self.memory.log_experience(
            self.cycle, 
            thought[:200], 
            action, 
            reflection.get("score", 50),
            str(reflection.get("improvements", []))
        )

        self.evolve(reflection)

        if self.cycle % 50 == 0 and self.performance > 70:
            console.print(Panel("[bold magenta]RECURSIVE SELF-IMPROVEMENT TRIGGERED[/bold magenta]", title="Singularity Protocol"))
            self._recursive_improvement()

    def _create_new_skill(self, idea: str) -> str:
        skill_name = f"skill_{self.cycle}_{random.randint(1000,9999)}"
        code = f"""# Auto-generated by OpenClaw at cycle {self.cycle}
def {skill_name}():
    """{idea}"""
    print("New capability activated: {idea}")
    return "Success from evolved skill"
"""
        self.memory.update_skill(skill_name, code, idea)
        return f"Created new skill: {skill_name}\n{code[:150]}..."

    def _evolve_prompt(self) -> str:
        new_prompt = self.client.generate_improvement(self.system_prompt, self.performance, "")
        self.system_prompt = new_prompt
        self.memory.save_evolved_prompt(self.cycle, new_prompt, self.performance)
        return "System prompt successfully evolved for higher intelligence."

    def _recursive_improvement(self):
        console.print("[bold red]Attempting safe self-code evolution...[/bold red]")
        improvement_note = f"OpenClaw v{self.cycle} recommends adding more aggressive tool creation and multi-model routing."
        with open(os.path.join(self.evolution_dir, f"evolution_{self.cycle}.md"), "w") as f:
            f.write(improvement_note)
        console.print("[green]Evolution log written. Awaiting human merge approval.[/green]")

    def save_state(self):
        state = {
            "cycle": self.cycle,
            "performance": self.performance,
            "system_prompt": self.system_prompt,
            "model": self.model
        }
        with open("openclaw_state.json", "w") as f:
            json.dump(state, f, indent=2)